Check for the existence of the tables specified by --table or --parent-table
PostgreSQL 14 will produce something like
 ERROR: pg_repack failed with error: ERROR:  relation "dummy_table" does not exist
 CONTEXT:  unnamed portal parameter $2 = '...'
The second line looks weird and breaks tests. The second word "ERROR" also looks strange. So an explicit check for the existence of a table has been added.