Merge upstream (#10)
* simple_prompt signature was changed

* Use SearchSysCacheCopy1 macro instead of SearchSysCacheCopy direct call as more future-proof

Per syscache.h:
> The use of the macros below rather than direct calls to the corresponding
> functions is encouraged, as it insulates the caller from changes in the
> maximum number of keys.

Also this fixes segfault on pg14, but still not sure why exactly.

* Get rid the custom array_accum aggregate in favor of postgresql's built-in array_agg and string_agg.

In postgresql 14, the signature of array_append was changed, and our create aggregate throws the error "function array_append(anyarray, anyelement) does not exist". Postgresql's built-in string_agg was introduced in postgresql 9.0, array_agg was from 8.4 release. Both are too old and no longer supported by pg_repack. So, instead of fixing the repack.array_accum, I want to drop it.
One notable behavior difference is handling empty sets: array_agg will produce NULL. So I put several coalesce to avoid altering the query results.

* Check for the existence of the tables specified by --table or --parent-table

PostgreSQL 14 will produce something like
 ERROR: pg_repack failed with error: ERROR:  relation "dummy_table" does not exist
 CONTEXT:  unnamed portal parameter $2 = '...'
The second line looks weird and breaks tests. The second word "ERROR" also looks strange. So an explicit check for the existence of a table has been added.

* Prepare release 1.4.7

First sketch to see what buildfarm thinks. Also recheck PGVER=9.6 build

* ubuntu xenial is EOL, try focal 20.04 LTS

* third party apt-repositories removed from the Bionic build image. Next try
https://docs.travis-ci.com/user/reference/bionic/#third-party-apt-repositories-removed

* amd64 packages only, please

* apt repository section was changed?

* postgresql-14 beta1 should be already in repo, retry

* try a workaround for pg9.5, 9.6
Possible we decide to drop these versions, but just check

* missing build dependency by postgresql-server-dev lz4

* update docs broken links

* Remove connection info from error log

* remove unnecessary plus operator

* fix typo in pgut.c

* Fix typo

Fix typo

* Reassure the user that it's ok to drop the extension

See #281

Co-authored-by: melkij <sk@zsrv.org>
Co-authored-by: Valeriya Popova <waleriya@yandex-team.ru>
Co-authored-by: Daniel Merken <daniel.merken@gmail.com>
Co-authored-by: lincuiping <57204139+lincuiping@users.noreply.github.com>
Co-authored-by: sunhm89 <93200340+sunhm89@users.noreply.github.com>
Co-authored-by: zhuqx-fnst <94515051+zhuqx-fnst@users.noreply.github.com>
Co-authored-by: Daniele Varrazzo <daniele.varrazzo@gmail.com>