set idle_in_transaction_session_timeout to 0
statement_timeout is being set to 0 in session preventing failures
when this parameter is non-zero. This change is to prevent failures due
to idle-in-transaction timeout, which look like this:

```
FATAL:  terminating connection due to idle-in-transaction timeout
ERROR: query failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
DETAIL: query was: SAVEPOINT repack_sp1
```